# Generated by Django 5.2.7 on 2025-10-20 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AITool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('intro', models.TextField(blank=True)),
                ('howto', models.TextField(blank=True)),
                ('link_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MissionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('intro', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SideHustleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('summary', models.TextField(blank=True)),
                ('pros', models.TextField(blank=True)),
                ('cons', models.TextField(blank=True)),
                ('link_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, max_length=120)),
                ('hero_sub', models.CharField(blank=True, max_length=200)),
                ('hero_cta_text', models.CharField(blank=True, max_length=50)),
                ('hero_cta_link', models.CharField(blank=True, max_length=120)),
                ('calendar_embed_src', models.URLField(blank=True, help_text='Googleカレンダーの埋め込みURL')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=120)),
                ('detail', models.TextField(blank=True)),
                ('resource_url', models.URLField(blank=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='content.roadmap')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrainingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(help_text='YouTubeの視聴URL（watch?v=... でも可）')),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.trainingcategory')),
            ],
        ),
    ]
