# Generated by Django 5.2.7 on 2025-11-27 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AITool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('intro', models.TextField(blank=True)),
                ('howto', models.TextField(blank=True)),
                ('link_url', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='ai_tools/')),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(blank=True, max_length=120)),
                ('hero_sub', models.CharField(blank=True, max_length=200)),
                ('hero_cta_text', models.CharField(blank=True, max_length=50)),
                ('hero_cta_link', models.CharField(blank=True, max_length=120)),
                ('calendar_embed_src', models.URLField(blank=True, help_text='Googleカレンダーの埋め込みURL')),
            ],
        ),
        migrations.CreateModel(
            name='FaqEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('apoint', 'アポイント'), ('knowledge', 'WOLFE事業知識'), ('sidejob', '副業コミュニティ'), ('request', '意見・要望'), ('other', 'その他')], default='other', max_length=20, verbose_name='カテゴリ')),
                ('question_text', models.TextField(help_text='複数の質問をまとめる場合は要約文でOKです。', verbose_name='Q&Aの質問内容（1つ or 複数の質問をまとめた要約）')),
                ('answer', models.TextField(verbose_name='回答内容')),
                ('is_published', models.BooleanField(default=True, verbose_name='サイトに公開する')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('home', 'ホーム')], db_index=True, default='home', max_length=20)),
                ('image', models.ImageField(upload_to='hero/')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='代替テキスト')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='掲載開始')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='掲載終了')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MissionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('info', '会社情報'), ('training', '研修'), ('event', 'イベント'), ('site', 'サイト'), ('others', 'その他')], max_length=50)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='固定表示')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Roadmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('intro', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SideHustleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('pocket', 'お小遣い案件'), ('career', 'キャリア支援'), ('life', '固定費削減'), ('other', 'その他')], default='pocket', max_length=20)),
                ('name', models.CharField(max_length=80)),
                ('summary', models.TextField(blank=True)),
                ('reward', models.CharField(blank=True, max_length=120)),
                ('pros', models.TextField(blank=True)),
                ('cons', models.TextField(blank=True)),
                ('link_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='side_hustle/', verbose_name='イメージ画像')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='匿名で投稿したい場合は空欄でOKです。', max_length=50, verbose_name='お名前')),
                ('category', models.CharField(choices=[('apoint', 'アポイント'), ('knowledge', 'WOLFE事業知識'), ('sidejob', '副業コミュニティ'), ('request', '意見・要望'), ('other', 'その他')], default='apoint', max_length=20, verbose_name='カテゴリ')),
                ('body', models.TextField(verbose_name='内容（質問・相談・ご意見など）')),
                ('status', models.CharField(choices=[('new', '未回答'), ('answered_private', '個別対応済み'), ('answered_public', 'Q&Aで回答済み'), ('no_action', '対応不要')], default='new', max_length=20, verbose_name='対応ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('faq_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='content.faqentry', verbose_name='紐づくQ&A')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=120)),
                ('detail', models.TextField(blank=True)),
                ('resource_url', models.URLField(blank=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='content.roadmap')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrainingVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(help_text='YouTubeの視聴URL（watch?v=... でも可）')),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('is_public', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='content.trainingcategory')),
            ],
        ),
    ]
