# Generated by Django 5.2.7 on 2026-01-02 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='summary',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='tag',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='RoadmapPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=1)),
                ('badge', models.CharField(blank=True, max_length=30)),
                ('minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('body', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('roadmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='content.roadmap')),
            ],
            options={
                'ordering': ('order', 'id'),
                'unique_together': {('roadmap', 'slug')},
            },
        ),
    ]
