# Generated by Django 5.2.7 on 2025-11-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('home', 'ホーム')], db_index=True, default='home', max_length=20)),
                ('image', models.ImageField(upload_to='hero/')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='代替テキスト')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='表示順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='掲載開始')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='掲載終了')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
