# Generated by Django 5.2.7 on 2025-11-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_heroimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidehustleitem',
            name='category',
            field=models.CharField(choices=[('pocket', 'お小遣い案件'), ('career', 'キャリア支援'), ('life', '固定費削減'), ('other', 'その他')], default='pocket', max_length=20, verbose_name='カテゴリ'),
        ),
        migrations.AddField(
            model_name='sidehustleitem',
            name='reward',
            field=models.CharField(blank=True, max_length=120, verbose_name='報酬・目安'),
        ),
        migrations.AlterField(
            model_name='sidehustleitem',
            name='cons',
            field=models.TextField(blank=True, verbose_name='留意点'),
        ),
        migrations.AlterField(
            model_name='sidehustleitem',
            name='link_url',
            field=models.URLField(blank=True, verbose_name='詳細リンク'),
        ),
        migrations.AlterField(
            model_name='sidehustleitem',
            name='name',
            field=models.CharField(max_length=80, verbose_name='案件名'),
        ),
        migrations.AlterField(
            model_name='sidehustleitem',
            name='pros',
            field=models.TextField(blank=True, verbose_name='ポイント・メリット'),
        ),
        migrations.AlterField(
            model_name='sidehustleitem',
            name='summary',
            field=models.TextField(blank=True, verbose_name='概要'),
        ),
    ]
