# Generated by Django 5.2.7 on 2026-01-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_roadmap_order_roadmap_summary_roadmap_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmappage',
            name='purpose',
            field=models.TextField(blank=True),
        ),
    ]
