# Generated by Django 5.2.7 on 2025-11-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_sidehustleitem_category_sidehustleitem_reward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sidehustleitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='side_hustle/', verbose_name='イメージ画像'),
        ),
        migrations.AlterField(
            model_name='sidehustleitem',
            name='category',
            field=models.CharField(choices=[('pocket', 'お小遣い案件'), ('career', 'キャリア支援'), ('life', '固定費削減'), ('other', 'その他')], default='pocket', max_length=20),
        ),
        migrations.AlterField(
            model_name='sidehustleitem',
            name='cons',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sidehustleitem',
            name='link_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sidehustleitem',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='sidehustleitem',
            name='pros',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sidehustleitem',
            name='reward',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='sidehustleitem',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
