# Generated by Django 5.2.7 on 2026-01-03 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_roadmappage_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmappage',
            name='minutes',
        ),
    ]
