# Generated by Django 5.2.7 on 2026-01-03 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_roadmappage_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmap',
            name='tag',
        ),
    ]
