# Generated by Django 5.2.7 on 2025-11-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_sidehustleitem_image_alter_sidehustleitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitool',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ai_tools/'),
        ),
    ]
