# Generated by Django 5.2.7 on 2026-01-03 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_roadmap_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Step',
        ),
    ]
