# Generated by Django 5.2.7 on 2026-01-03 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_delete_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmap',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='roadmappage',
            name='purpose',
        ),
    ]
