# Generated by Django 5.2.7 on 2026-01-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_roadmap_intro_remove_roadmappage_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmappage',
            name='badge',
        ),
        migrations.AddField(
            model_name='roadmappage',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='roadmap_covers/', verbose_name='カバー画像'),
        ),
    ]
