# Generated by Django 5.2.7 on 2026-01-03 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_remove_roadmappage_badge_roadmappage_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='roadmap_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='roadmap_home/', verbose_name='ロードマップHOMEカバー画像'),
        ),
    ]
