# Generated by Django 5.2.7 on 2026-01-03 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_calendar_roadmap_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='hero_cta_link',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='hero_cta_text',
        ),
    ]
