# Generated by Django 5.2.7 on 2026-01-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_remove_calendar_hero_cta_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadmap',
            name='order',
            field=models.DecimalField(db_index=True, decimal_places=1, default=1, max_digits=4),
        ),
    ]
