# Generated by Django 5.2.7 on 2026-01-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_roadmap_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='kind',
            field=models.CharField(choices=[('step', 'STEP'), ('extra', 'EXTRA')], db_index=True, default='step', max_length=10),
        ),
    ]
