# Generated by Django 5.2.7 on 2026-01-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_roadmap_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sidehustleitem',
            name='cons',
        ),
        migrations.RemoveField(
            model_name='sidehustleitem',
            name='pros',
        ),
    ]
