# Generated by Django 5.2.7 on 2026-03-31 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_remove_sidehustleitem_cons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='faq_entry',
        ),
        migrations.DeleteModel(
            name='FaqEntry',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
