# Generated by Django 5.2.7 on 2026-03-31 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_remove_question_faq_entry_delete_faqentry_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
