# Generated by Django 5.2.7 on 2026-03-31 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_delete_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SideHustleItem',
        ),
    ]
